@startuml

skinparam monochrome true
allowmixing

package "Domainmodel Converge" {

actor User
actor Administrator
actor System

object Audit {
  trail
}
object Authentication {
  email
  password
}
object Authorization {
  role
}
object Project {
  freelancer
  employer
  bids
  amount
  date
}
object Chat {
  messages
}
object Collaboration {
  messages
  files
  rating
}
object Payments {
  accounts
}
object Profile {
  email
  name
  rating
  skills
  experience
  description
}
object Monitoring {
  tracing
  metrics
  logging
}
object Administration

User -up-> Authentication: Can authenticate  
User -up-> Authorization: can authorize
Authentication --> Audit: logs trail

User -left-> Chat: send message
Chat -right-> User: send message
User --> Project: Can bid or create project
Project --> Collaboration: Can collaborate
User --> Collaboration: Can interact
Collaboration --> Payments: Can facilitate payments

User -right-> Profile: Has a

Payments -left-> Audit: Can log trail
Collaboration -left-> Audit: Can log trail

Administrator --> Monitoring: Can monitor
Monitoring --> System: can monitor system
Administrator --> Administration: Can administrator
Administration --> User: Can administrate user


  
}

@enduml