@startuml

skinparam monochrome true
skinparam classAttributeIconSize 0

!function service($name)

!$service = "Service"
!$application = "Application"
!$database = "Database"

!$serviceName = $name + $service
node $serviceName {
    !$applicationName = $name + $application
    node $applicationName [
            <<ExecutionEnvironment>>
            <b>ASP.NET Core Web API
            ---
            $applicationName
        ]

    !$databaseName = $name + $database
    database $databaseName [
            <<ExecutionEnvironment>>
            <b>MongoDB
            ---
            $databaseName
        ]

        $applicationName -down-(0 $databaseName

Træfik --(0 $serviceName
}

!endfunction
package "deployment Converge-cluster" {

    node Træfik {

    }

    service("Audit")
    service("Authentication")
    service("Biddings")
    service("Broker")
    service("Chat")

    service("Collaboration")
    service("Files")
    service("Payments")
    service("Profiles")
    service("Projects")
    service("Users")
}
@enduml