
@startuml
skinparam rectangle {
	roundCorner 25
  
}

skinparam monochrome true
top to bottom direction
package "Converge workflows" {
rectangle "Higher order React component" as Converge {
	rectangle "User interface \n React component" as sa 
}

rectangle "Service End Points" as service   {
	rectangle "Services" 
}

rectangle "Redux store" as redux{
	rectangle "Reducers"
  rectangle "Middleware"

}


rectangle "Request Module" as request
rectangle "Action" as action
rectangle "New State" as newState
rectangle "Http request" as http
rectangle "Http response" as response

  sa --> request
  request --> http
  http --> service
  response <-- service
  redux <-- response
  newState <-- redux
  Converge <-- newState
  sa --> action
  action --> redux


}
@enduml