@startuml
hide footbox
autonumber "<b>[0]"
skinparam monochrome true

actor Employer
participant PostProjectService

activate Employer
Employer -> PostProjectService: Project information

activate PostProjectService
PostProjectService -> PostProjectService: Creates new project
PostProjectService -> Employer: Confirms Projectet created
@enduml