@startuml
hide footbox
autonumber "<b>[0]"
skinparam monochrome true

actor User
participant SearchService

activate User
User -> SearchService: Search keyword

activate SearchService
SearchService -> SearchService: Filter search keyword
SearchService --> User: Display result

activate User
User -> User: Delete filter
@enduml
