@startuml
hide footbox
autonumber "<b>[0]"
skinparam monochrome true

actor User

participant ProfilService

activate User
User ->  ProfilService: Change account settings

activate  ProfilService
 ProfilService ->  ProfilService: Save and apply new settings
 ProfilService --> User: Comfirms account settings 
@enduml
