@startuml Components 

skinparam BackgroundColor transparent
skinparam Monochrome true
skinparam shadowing false

package "Component Converge-system" as cp {

[Audit-service] as audit
[Users-service] as users
[Authentication-service] as auth
[Projects-service] as projects
[Broker-service] as broker
[Collaboration-service] as collaboration
[Files-service] as files
[Payments-service] as payments
[Profile-service] as profiles
[Client] as client
[Gateway-service] as gateway
[Bidding-service] as bidding
[Chat-service] as chat

auth --> users
profiles --> users
projects --> users
collaboration --> projects
broker --> collaboration
profiles --> files
collaboration --> files
client --> gateway
bidding --> users
bidding --> projects
broker --> payments
users --> payments
users --> chat
auth --> audit
collaboration --> audit
payments --> audit

note right of gateway : Connects to all other services


}

@enduml
