@startuml
hide footbox
autonumber "<b>[0]"
skinparam monochrome true

actor Admin
participant UserService

activate Admin
Admin -> UserService: Restore a user

activate UserService
UserService -> UserService: Checking for user
UserService --> Admin: Confirms user is restored


@enduml
