@startuml
hide footbox
autonumber "<b>[0]"
skinparam monochrome true

actor Admin
participant UserService

activate Admin
Admin -> UserService: see user reports

activate UserService
UserService -> UserService: Checking user reports
UserService --> Admin: Something is wrong


@enduml
